# Generated by Django 4.2.4 on 2023-10-11 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0002_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='texto',
            new_name='corpo',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='status',
        ),
        migrations.AddField(
            model_name='comentario',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='atualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_coments', to='postagens.postagem'),
        ),
    ]
